# random seed
random_seed: 66

# data precision
precision: float32

# gpu
gpu: true
gpu_index: '0,1,2'
addr: 'localhost'
port: '12388'

# super parameters
epochs: 500
learning_rate: 1.0e-3
steplr_size: 100
steplr_gamma: 0.96
shuffle: false
batch_size: 8

# experiment name and path
experiment_name: '1'
continuous_train: false
checkpoint_path: '/home/zengbocheng/Projects/torch_parallel/checkpoints/checkpoint{}.pt'
figs_loss_train: '/home/zengbocheng/Projects/torch_parallel/figs/train_{}.pdf'

# log
log_file: 'logs/out{}.log'